name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y cmake make #install cmake to build
      #change to run tests from a tests.cpp file instead
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
