name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y cmake make #install cmake to build
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
