name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Code Coverage Tools
      run: |
        choco install codecov -y
        choco install reportgenerator -y
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Install dependencies
      run: |
        nuget restore "drum machine/drum machine.sln"
        
    - name: Build solution
      run: |
        msbuild /m /p:Configuration=Release "drum machine/drum machine.sln" /p:EnableCodeCoverage=true

    - name: Run Tests
      run: |
        vstest.console.exe "bin/x64/Release/drum machine.dll" /EnableCodeCoverage

    - name: Generate Code Coverage Report
      run: |
        reportgenerator "-reports:**\*.coveragexml" "-targetdir:coverage-report" -reporttypes:Cobertura

    - name: Upload coverage to Codacy
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        codacy-coverage-reporter report -r coverage-report/Cobertura.xml
