name: Generate-Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docs:

    runs-on: windows-latest

    steps:
    
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.9.8
      with:
        doxyfile-path: './Doxygen'

